baseURL = "https://www.skycoin.com/docs"
languageCode = "en-us"
title = "Skycoin Documentation"
defaultContentLanguage = "en"

relativeURLs = true
canonifyURLs = true


googleAnalytics = "UA-105234182-1"
disqusShortname = ""

# hugo-xmin specific variables
theme = "skycoin"

ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

# enables ```lang ``` style syntax highlighted blocks
pygmentsCodeFences = true
pygmentsStyle = "murphy"
pygmentsCodeFencesGuessSyntax = true

[permalinks]
# guides = "/guides/:year/:month/:day/:slug/"
# references = "/references/:year/:month/:day/:slug/"
# note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Blog"
    identifier = "blog"
    url = "/blog/"
    weight = 5
[[menu.main]]
    name = "Explorer"
    identifier = "explorer"
    url = "//explorer.skycoin.com"
    weight = 6
[[menu.main]]
    name = "Downloads"
    identifier = "wallet"
    url = "/downloads/"
    weight = 1
[[menu.main]]
    name = "Team"
    identifier = "team"
    url = "/team/"
    weight = 4
[[menu.main]]
    name = "Ecosystem"
    identifier = "ecosystem"
    url = "/ecosystem/"
    weight = 2
[[menu.main]]
    name = "Skyminer"
    identifier = "skyminer"
    url = "/skyminer/"
    weight = 3
#[[menu.main]]
#    name = "Documents"
#    identifier = "docs"
#    url = "/docs/"
#    weight = 6

[[menu.docs]]
name = "User Guides"
identifier = "user-guides"
url = "/user-guides/"
weight = 1

[[menu.docs]]
name = "Developer docs"
identifier = "devdocs"
url = "/dev-docs/"
weight = 2

[[menu.devdocs]]
name="Guides"
identifier="guides"
url = "/dev-docs/guides/"
weight = 1

[[menu.devdocs]]
name="References"
identifier="references"
url = "/dev-docs/references/"
weight = 2

# [[menu.devdocs]]
# name="Examples"
# identifier="example"
# url = "/dev-docs/examples/"
# weight = 3

[[menu.devdocs]]
name="Glossary"
identifier="glossary"
url = "/glossary/"
weight = 4


[author]
name = "Skycoin"

[params]
keywords = "skycoin"
rss = "/index.xml"
telegram = "https://t.me/Skycoin"
discord = "https://discord.gg/EgBenrW"
description = "Skycoin Project Updates"
email = ""
github = "skycoin"
twitter = "skycoinproject"
twitterAnalytics = "ny03t"
urlGit = "https://github.com/SkycoinProject/docs"

[[params.social]]
  name = "Medium"
  url = "/"
  image = "images/medium.svg"
[[params.social]]
  name = "Twitter"
  url = "https://twitter.com/skycoinproject"
  image = "images/twitter.svg"
[[params.social]]
  name = "Facebook"
  url = "https://www.facebook.com/SkycoinOfficial/"
  image = "images/facebook.svg"
[[params.social]]
  name = "Instagram"
  url = "https://www.instagram.com/skycoinproject/"
  image = "images/instagram.svg"
[[params.social]]
  name = "Github"
  url = "https://github.com/SkycoinProject/skycoin"
  image = "images/github.svg"
[[params.social]]
  name = "Youtube"
  url = "https://www.youtube.com/c/Skycoin"
  image = "images/youtube.svg"
[[params.social]]
  name = "Reddit"
  url = "https://www.reddit.com/r/SkycoinProject"
  image = "images/reddit.svg"
[[params.social]]
  name = "Apple"
  url = "https://itunes.apple.com/nl/podcast/skycoin/id1348472259?l=en"
  image = "images/apple.svg"
[[params.social]]
  name = "Discord"
  url = "https://discord.gg/EgBenrW"
  image = "images/discord.svg"
[[params.social]]
  name = "Telegram"
  url = "https://t.me/Skycoin"
  image = "images/telegram.svg"

[[menu.languages]]
name = "English"
weight = -1
url = "/"

[Languages]
[Languages.en]
weight = -1
title = "Skycoin Documentation"
languageName = "English"
